documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'go.*'
          - 'docs/go.*'

pipelines:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
