version: "2"
linters:
  enable:
    - bodyclose
    - contextcheck
    - depguard
    - durationcheck
    - dupl
    - errchkjson
    - errname
    - exhaustive
    - exportloopref
    - govet
    - goimports
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - revive
    # - rowserrcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    # - wastedassign
    - whitespace
