package vault_test

import (
	"os"
	"testing"

	"github.com/byteness/aws-vault/v7/vault"
)

// Regression test for https://github.com/ByteNess/aws-vault/issues/389
//
// A role profile that sources its credentials from another profile, but does
// not define its own mfa_process, should inherit the source profile's
// mfa_process. Before the fix the MFA token was prompted interactively instead
// of being generated by the source profile's mfa_process command.
var issue389Config = []byte(`
[profile fooprofile]
credential_process = aws-vault export --debug --format=json fooprofile
mfa_process = op item get 'AWS Login' --otp
mfa_serial = arn:aws:iam::123456789012:mfa/me
region = us-east-1

[profile barprofile]
mfa_serial = arn:aws:iam::123456789012:mfa/me
region = us-east-1
role_arn = arn:aws:iam::987654321098:role/Administrator
source_profile = fooprofile
`)

func TestMfaProcessInheritedFromSourceProfile(t *testing.T) {
	f := newConfigFile(t, issue389Config)
	defer os.Remove(f)

	cf, err := vault.LoadConfig(f)
	if err != nil {
		t.Fatal(err)
	}
	loader := &vault.ConfigLoader{File: cf, ActiveProfile: "barprofile"}
	config, err := loader.GetProfileConfig("barprofile")
	if err != nil {
		t.Fatal(err)
	}

	want := "op item get 'AWS Login' --otp"
	if config.MfaProcess != want {
		t.Errorf("barprofile.MfaProcess = %q, want %q (mfa_process should be inherited from source_profile)", config.MfaProcess, want)
	}
}

// A profile that defines its own mfa_process must keep it and not have it
// overwritten by the source profile's mfa_process.
func TestMfaProcessOnProfileNotOverriddenBySource(t *testing.T) {
	cfg := []byte(`
[profile source]
mfa_process = source-otp
mfa_serial = arn:aws:iam::123456789012:mfa/me
region = us-east-1

[profile target]
mfa_process = target-otp
mfa_serial = arn:aws:iam::123456789012:mfa/me
role_arn = arn:aws:iam::987654321098:role/Administrator
source_profile = source
region = us-east-1
`)
	f := newConfigFile(t, cfg)
	defer os.Remove(f)

	cf, err := vault.LoadConfig(f)
	if err != nil {
		t.Fatal(err)
	}
	loader := &vault.ConfigLoader{File: cf, ActiveProfile: "target"}
	config, err := loader.GetProfileConfig("target")
	if err != nil {
		t.Fatal(err)
	}

	if config.MfaProcess != "target-otp" {
		t.Errorf("target.MfaProcess = %q, want %q (own mfa_process must take precedence)", config.MfaProcess, "target-otp")
	}
}
